#!/usr/bin/env bash

if which jq aws >/dev/null && \
    [ ! -z "$AWS_ACCESS_KEY_ID" ] ; then
  AWS_ACCOUNT_ID="$(aws iam get-user | jq -r .User.Arn | awk -F : '{print $5;}')"

  color_clear="\[\e[m\]"
  color_red="\[\e[1;31m\]"
  color_green="\[\e[1;32m\]"
  color_blue="\[\e[1;34m\]"
  color_yellow="\[\e[1;33m\]"

  case "${AWS_ACCOUNT_ID}" in
    "11111111111111")
      AWS_ACCOUNT="aws-dev"
      COLOR="$color_green"
      ;;

    "2222222222222")
      AWS_ACCOUNT="aws-stg"
      COLOR="$color_yellow"
      ;;

    "3333333333333")
      AWS_ACCOUNT="aws-prod"
      COLOR="$color_red"
      ;;

    "4444444444444")
      AWS_ACCOUNT="aws-2-prod"
      COLOR="$color_red"
      ;;

    "5555555555555")
      AWS_ACCOUNT="aws-2-dev"
      COLOR="$color_green"
      ;;

    *)
      AWS_ACCOUNT="unknown"
      ;;
  esac

  # Remove any previous aws env set
  PS1=$(echo $PS1|sed -e 's|\\\[\\e\[1\;[[:digit:]]\+m\\\]\[.*\]\\\[\\e\[m\\\] ||g')

  # Set new env
  PS1="$(printf '%s[%s]%s\n' "$COLOR" "$AWS_ACCOUNT" "$color_clear") $PS1 "

  unset COLOR color_clear color_red color_green color_blue color_yellow
fi
